services:
  felicia:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    env_file:
      - .env
